#!/bin/bash
rm db/*
rm -rf db/labels
rm db/cards/yyu*
mkdir -p db/labels
mkdir db/cards
library new-book --title "Theoretical Physics" --author "Georg Joos" -j --book /dev/null -u /dev/null
library add-user -u "Vanessa McHale" -e "tmchale@wisc.edu" --book /dev/null -u /dev/null -j
library add-user -u "Margaret Babe" -e "mbabe@wisc.edu" --book /dev/null -u /dev/null -j
library print-card -e "tmchale@wisc.edu" -u /dev/null --book /dev/null
library print-card -e "mbabe@wisc.edu" -u /dev/null --book /dev/null
library checkout -u "db/patron.json" --book "db/library.json" -j
mkCards && gnome-open hamlet/cards/mbabe.html
parse-ris
